### PR TITLE
Deploy medium nsxt manager

### PR DESCRIPTION
**Pull request by Knappek**

### CODE REVIEW

**Comment by laidbackware** [comment]
What's the reason to change the NSX Manager sizing to medium, as small is OK for most lab environments. Instead of changing the default for all to medium you could set the default to small and then allow it to be overridden to medium.

Also what is the reason for adding the tags "always"?

**Comment by Knappek** [comment]
made `deployment_option` configurable. I had to change it to medium as my nsx-t manager threw an error that it was running out of memory.

Reason for tags "always" is: If you run the playbook with tags, e.g. appending `--tags tkgs` the playbook didn't run the pre-tasks and it failed because the variable `temp_dir` was undefined.

**Comment by laidbackware** [comment]
Thanks for adding the default.

I added the "pre" tag to force pre-tasks to run when you add tags for a role that needs the temp_dir. So you would just use that instead.

**Comment by Knappek** [comment]
so this means anytime I am using tags I always have to use the "pre" tag? So instead of running `ansible-playbook .... --tags nsxt,tkgs` I have to use `ansible-playbook .... --tags pre,nsxt,tkgs`? Wouldn't it be easier to just use the [always tag](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#special-tags-always-and-never) ?

**Comment by laidbackware** [comment]
Agreed if re-implementing today that always as the tag label makes more sense, but changing now could confuse anyone already using and and adding a second tag for the same purpose might be confusing.

**Comment by laidbackware** [comment]
Also only a minority of roles require the pre-tasks. There could even be an argument to just move any temp directory creation out to the roles where needed and remove the pre-tasks.

**Comment by Knappek** [comment]
shouldn't we replace `pre` with `always` as always is built-in Ansible and "pre" doesn't really have a meaning. When using "pre", then `ansible-playbook .... --tags tkgs` fails. When using "always", then `ansible-playbook ... --tags tkgs` does not fail.
People already working with `--tags pre,any-other-tag` will experience the same playbook run where any task with tag "any-other-tag" will be executed AND pre-tasks as well because of the "always" tag. In this case, "pre" will be ignored because it doesn't exist on any of the tasks.

I'm okay if you still want to keep "pre" and don't use "always", but I wanted to insist with this last comment ;). Let me know and I'll change accordingly.

**Comment by laidbackware** [comment]
Searching the code it seems like the NSX manager role is the only one using the pre-tasks, so you could also just copy the logic from the NSX principal identity role then just remove the pre-tasks completely.

**Review by laidbackware — APPROVED** [review]
LGTM

**Pull request merged**
